# テスト用の外部例外クラス
class ExternalError(Exception):
    pass
